### PR TITLE
Reduced several lines

### PR DESCRIPTION
**Pull request by rivertam**
As far as I know, this makes the code equally efficient and slightly more readable.

### CODE REVIEW

**Comment by rivertam** [comment]
Apologies if I've done something wrong: I've pretty much never even used Pixi.js or contributed to open source, but this seemed like an innocuous change.

**Comment by englercj** [comment]
Can you create a jsperf that proves this is the same or faster? Looks like a good change if it is, but I'm not sure that the function call overhead is cheaper..

**Comment by rivertam** [comment]
Apologies. I looked this up beforehand and found a StackOverflow question and attached jsperf which revealed very similar results, but I created a jsperf that directly compares what this code is actually doing and found that the current way is much better than the proposed way.

JSPerf here: http://jsperf.com/math-min-vs-ternary-operators

**Comment by englercj** [comment]
All good, I had a hunch that might have been the case. Thanks for taking the time to look into this!

**Pull request closed without merging**
