### PR TITLE
Replace PolyK with Earcut

### PR DESCRIPTION
**Pull request by englercj**
Want to get this merged in, will leave open for a bit for review if anyone wants to help me out :)

@mourner - Finally happening, sorry it took so long!

Fixes: #1665

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
nice! will take a look - do we know if this is faster?

**Comment by mourner** [comment]
@englercj awesome, looking forward to see this in action! Would love to see some before/after benchmarks too. :) I'm sure it's faster, especially on shapes with lots of points, but a proof will be comforting.

@GoodBoyDigital other than performance, two more benefits you should be aware of:

- it's much more robust — e.g. won't crash on bad data and much more likely to triangulate correctly when dealing with degenerate geometries
- it supports holes in case you want to add support for them in future

**Comment by englercj** [comment]
@GoodBoyDigital Yes, it is faster than PolyK plus the things that @mourner mentioned.

I want this to go in so we can draw polygons with holes in `Graphics` objects. I've gotten a couple asks for that now.

**Comment by Priyank30** [comment]
@mourner 
I have previously used Earcut library with threejs to improve better triangulation calculation and performance and,  indeed it is a better in both prospects then threejs native triangulation algorithm. 
But in some of my test it fails on two case:
1) When holes are intersects
2) Hole entirely does not belongs to the shape.
Is there any fix for it?  
It might not be the correct place to ask about earcut solution but now I'm using PixiJs instead of Threejs and I found this thread because @englercj  has referenced it in my question #1755 so just want address some issue.

**Comment by mourner** [comment]
@Priyank30 report the specific test cases in Earcut issues and I'll look if it can be helped. As far as I'm aware, no triangulation library can handle situations like that gracefully. 

The only reliable solution I can think of is to preprocess the data with something like http://sourceforge.net/projects/jsclipper/, correcting the topological errors with holes.

**Comment by mourner** [comment]
@GoodBoyDigital @englercj updated the perf table to include PolyK: https://github.com/mapbox/earcut. Earcut is roughly 3-4 times faster.

Also released version 2.0.1 which adds support for Steiner points (additional vertices inside polygons).

**Comment by GoodBoyDigital** [comment]
oooh! this is great news :D
Im convinced, thanks for making such a nice tool!

**Pull request merged**
