### PR TITLE
Feature/test init

### PR DESCRIPTION
**Pull request by drkibitz**
- Upgrade browserify to 9.x
- Adds karma-browserify and change from chai to karma-chai
- Moves all old unit tests to unit/pixi-v2

`gulp test` no longer runs tests in pixi-v2, but it does run 2 tiny new confirmation tests.

### CODE REVIEW

**Comment by englercj** [comment]
How do you feel about using testem instead of Karma? I've had much better experiences with it and was thinking about switching over.

**Comment by drkibitz** [comment]
@englercj haven't used it on a project of my own. I saw you are using in your resource-loader project, and I got it set up there in no time. Seems fine as long is it can run in a CI environment.

**Comment by englercj** [comment]
Definitely does, after I finish up some bugs I'll integrate the new test suite. Thanks!

**Comment by englercj** [comment]
Just committed a new framework using testem and added some simple tests to start:

3b3f9489c25f4cf2975105582d7f77b1b4c724a7

**Comment by drkibitz** [comment]
@englercj thank you sir, I'll give it a shot a little later.

**Comment by drkibitz** [comment]
@englercj works great, great job! and goodbye karma ;)

**Comment by englercj** [comment]
The `testem` local runner is amazing (`npm i -g testem` then run `testem` in pixi's folder). It runs the tests as you write them in multiple browsers and optionally node, and it feels super lightweight I love it.

Karma always felt super heavy :/

**Pull request merged**
