### PR TITLE
Convert the lib to use EE3

### PR DESCRIPTION
**Pull request by englercj**
This replaces the custom event implementation with [EventEmitter3](https://github.com/primus/eventemitter3).

### CODE REVIEW

**Comment by englercj** [comment]
If merged, this would close #1511.

**Comment by GoodBoyDigital** [comment]
Nice nice! Think we should also go through the code base and remove any ```bind()``` instances as this emitter class lets you pass in a scope property as a third param :+1:

**Comment by englercj** [comment]
@GoodBoyDigital Good call, didn't even think about that. I'll do it now.

**Comment by GoodBoyDigital** [comment]
:+1:

**Pull request merged**
