### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by JanAmbrozic**
Fix for #1331

### CODE REVIEW

**Comment by englercj** [comment]
I'm curious what situation occurs that causes the crop to be wrong? Also this code creates a new object each frame which is then discarded. We definitely don't want to do that.

**Comment by JanAmbrozic** [comment]
Yeah I was thinking about that object, I'll remove it later and issue a new PR. Wasn't sure if you have any preferred way of "normalising" variables in cases like that.

I will create a test case tomorrow but essentially if you drop image out of memory this happens. And only way to really remove the image out of memory (that we know off) is to replace it with 1x1 px "fake"  image. And when this happens the crop width/height are still from original image and not 1x1 like they should be. That is only the case in IE's though, works as expected in other browsers.

**Comment by englercj** [comment]
I'm more interested in what pixi code you are running to do that. If you are setting `texture.baseTexture.source` directly that isn't how that is supposed to work.

In v3 there are better methods for making a  texture be removed from gl memory, and for loading new sources.

**Comment by JanAmbrozic** [comment]
I spent a bit more time investigating this and I will decline my PR. The problem is actually not there but the real problem is because the width and height don't get updated no matter what I do.

We have a pool of images that we add to the PIXI.TextureCache and when one of them is unloaded we just change the source of the DOM image element to the 1x1px fake image. The only thing I want to achieve now is to update crop width and height. I tried setting "requiresUpdate" of baseTexture to true, I tried using "updateSourceImage" method and so on. 

I checked the code of baseTexture/Texture and I've seen that crop is only being updated in the "setFrame" method. I'm just wondering if that is intentionally or are you maybe missing crop update somewhere.

If I update the crop manually the issue disappears and everything is fine
```javascript
PIXI.TextureCache[imageAsset].crop.width = 1;
PIXI.TextureCache[imageAsset].crop.height = 1;
```

**Comment by englercj** [comment]
So obviously our code can't handle it if you do `PIXI.TextureCache[imageAsset].baseTexture.source.src = ''`. Instead you should probably delete the texture (`texture.destroy(true)`) and load something else later.

**Comment by JanAmbrozic** [comment]
It's not just changing the src to '', but to the new image. But regardless I fixed it with that crop adjustment and since it only affects IE10/11 it's not the best place to put it in sprite.js like you said.

Than you for all the help and sorry for wasting your time :)

**Pull request closed without merging**
