### PR TITLE
Moved ticker to core

### PR DESCRIPTION
**Pull request by drkibitz**
Take it or leave it ;)

This was just getting annoying to me since it's a shared module across extras and interaction modules.

### CODE REVIEW

**Comment by englercj** [comment]
I think this makes sense, @GoodBoyDigital?

**Comment by englercj** [comment]
@drkibitz Can you put something in the deprecation file with this since it is changing namespaces? If you put that in I will merge it :)

**Comment by drkibitz** [comment]
@englercj if you look closer, you'll notice that it actually didn't change namespaces :neckbeard:. It just moved module location (to reflect it's usage + namespace).

**Comment by englercj** [comment]
oh you got me there!

**Pull request merged**
