### PR TITLE
Fix an error when an event occurs on deleted obj

### PR DESCRIPTION
**Pull request by JiDW**
fix https://github.com/GoodBoyDigital/pixi.js/issues/1817

### CODE REVIEW

**Comment by englercj** [comment]
I feel like this just hides the symptom, I want to track down the cause and fix it.

**Comment by JiDW** [comment]
I think you're right. Thinking about it, I find it odd to see this error reported on the same day that it occured to me on a old code.

I did change things, however, like setting the shared ticker update at the start of my main loop.

For now, the temp "fix" is visibily enough but it is worth investigating.

**Comment by drkibitz** [comment]
Objects in pixi that can be destroyed in the render loop could use a `.destroyed` property flag. Would help with situations like this, and potentially more we haven't found or encountered yet.

**Comment by endel** [comment]
I'm curious to see a minimal example to reproduce this problem. Do you guys have one? It would be great to write some test cases to avoid this situation.

**Pull request merged**
