### PR TITLE
Fix for loadFramedSpriteSheet crash when the texture is not loaded yet

### PR DESCRIPTION
**Pull request by alaa-eddine**
this was posted by error in v3 branch :)

### CODE REVIEW

**Comment by Moeberg** [comment]
I have had trouble with this function. Would some one care to give an example of correct usages of this function?

**Comment by alaa-eddine** [comment]
I suggested this function for Pixi v1 because I needed it but didn't found any equivalent.
it mainly load a spritesheet and split it so you can use each sprite as separate pixi texture.

here is the original post with an example, it's quite old but will show you hot to use it http://www.html5gamedevs.com/topic/1278-loading-uniform-sprite-sheets-not-texturepacker-based/

hope it helps

**Comment by Moeberg** [comment]
Yes I stumbled upon this thread earlier and it works correctly under those circumstances when frames are passed trough a callback function, but the function you wrote for the framework don't have that options which is what throws me off. 

Also the example you linked returns a empty array so I am not able to define in variable which is what I am trying to do.

**Comment by alaa-eddine** [comment]
oh sorry here is an example :)


```javascript
var image = new PIXI.ImageLoader(image_url);
image.loadFramedSpriteSheet(width, height, 'mySpriteSheet');
//image.frames contains the loaded frames but you can't be sure that they are all available for this you need to listen for loaded event

pixiData.image.addEventListener("loaded", function (event) {
	var frames = image.frames; 

       //example of sprite instantiation using a the sprite at index 0
       var sprite = new PIXI.Sprite(frames['mySpriteSheet-0']);

}
```

**Comment by Moeberg** [comment]
Thank you that helped a lot!

**Pull request merged**
