### PR TITLE
More flexibility with multitouch gesture events (Advances, Optimization, ConconJS)

### PR DESCRIPTION
**Pull request by SirKnightDragoon**
* Add the global position on all changedTouches object
* Best way to gesture the double tap event on touchstart and getting each position.
* add optimisation and speed up the code
* add compatibility support for CocoonJS
* add more optimization

### CODE REVIEW

**Comment by SirKnightDragoon** [comment]
@englercj Now in the v2.x :+1:

**Comment by englercj** [comment]
Nice! I'll review this weekend!

**Comment by englercj** [comment]
Cool man, how do you feel about doing a similar PR for v3? To the `dev` branch?

**Comment by SirKnightDragoon** [comment]
I'm on it ;)

**Pull request merged**
