### PR TITLE
Improved Particle Shader performance by discarding transparent pixels

### PR DESCRIPTION
**Pull request by bchevalier**
On my machine the impact was a 50% fps boost on the bunnymark with 50,000 bunnies:
-Before: 30fps
-After: 45fps

### CODE REVIEW

**Comment by choser** [comment]
unsubscribe me from this mailinglist please

**Comment by GoodBoyDigital** [comment]
Now that is interesting! Which device / browser is this tested on?

Cheers!

**Comment by bchevalier** [comment]
Chrome, last version on a macbook pro

**Comment by englercj** [comment]
Good call, this is a great improvement. Needs to be a PR against `dev` though XD

**Comment by bchevalier** [comment]
Roger that. Making a PR on dev.

**Pull request closed without merging**
