### PR TITLE
Fix tilingsprite from a spritesheet

### PR DESCRIPTION
**Pull request by JiDW**
Fix https://github.com/GoodBoyDigital/pixi.js/issues/1787

When rendering a tilingsprite, we should use the frame and not the trimmed texture.

Thanks @greewi for this one.

I used tileScale to determine if the sprite is a tilingsprite. Tell me if you know a better way.

### CODE REVIEW

**Comment by englercj** [comment]
Wow, very interesting. @GoodBoyDigital is there a better check to see if it is a tilingsprite?

**Comment by GoodBoyDigital** [comment]
Hmm, I think there is a nicer way to do this to avoid the extra check. Leave it with me chaps!

**Comment by GoodBoyDigital** [comment]
Will have a think about this one.. wound be nice to find a way that does not involve modifying the spriteRenderer.  We should move the check to the tilingSprite class if we can..

**Comment by JiDW** [comment]
Any updates on this please ? Could be nice to be able to update our project to the latest build

**Comment by englercj** [comment]
Merging this for now, if @GoodBoyDigital has a better way we can refactor it.

**Pull request merged**
