### PR TITLE
Fix WebGLFilterManager to use renderSession.resolution

### LINKED ISSUE #1215: Filters and Custom Renderer Resolution Bug
Hello, so I've found a rather weird issue concerning filters and custom resolutions with Pixi.

See [here](http://jsfiddle.net/amadeus/j5c5wtq5/) for a quick example - click to toggle the filter on and off.

Essentially it seems like the entire scene gets scaled back down to 1x resolution, and attached to the bottom left corner. I've tried it with a couple other filters so it's not specific to the invert filter.

It's rather simple code - the only thing perhaps out of the ordinary is how I am instantiating my renderer:

```js
renderer = new PIXI.WebGLRenderer(
	446,
	250,
	{
		view: document.getElementById('canvas'),
		resolution: 3
	}
);
```

If I change resolution to 1, no problems at all.

### PR DESCRIPTION
**Pull request by amadeus**
Weird, I thought if I fixed the branch and force pushed, it should've updated #1397.

Perhaps because it was closed?

Anyways, this has been updated as per the discussion.

And for reference, it fixes #1215

### CODE REVIEW

**Comment by englercj** [comment]
Looks good to me, +review @GoodBoyDigital

**Comment by amadeus** [comment]
@edankwan had a good point about the filter's not scaling. Is there an easy fix I could add to this to make that happen? Or is that something far more in-depth?

**Comment by amadeus** [comment]
Just a quick bump on this.

**Comment by englercj** [comment]
Same comments as #1398, even if I merged it now. @GoodBoyDigital may take it out during his resolution rewrite.

**Comment by GoodBoyDigital** [comment]
All fixed up in v3 :+1:
Default resolution for filters is the same as the renderer

**Comment by amadeus** [comment]
@GoodBoyDigital This PR was meant for the `2.x` branch since I figured 3.0 would've fixed it in a different way. Is there a plan to backport a fix like this to `2.x`?

**Comment by englercj** [comment]
Didn't even notice this was a PR to the 2.x branch, I'll merge it in.

**Comment by amadeus** [comment]
You guys rock, thanks!

**Pull request merged**
