### PR TITLE
Add convenience event 'clicktap' that combines events for 'click' and 'tap'

### PR DESCRIPTION
**Pull request by marekventur**
Disclaimer: I'm not sure this is the best way of doing it.

In our code we have a few places where we do
```javascript
container.once("click", doSomething);
container.once("tap", doSomething);
```

This PR adds a new event called "clicktap" that combines the two:
```javascript
container.once("clicktap", doSomething);
```

I've run testem (some of the tests timed out), ~~but I couldn't figure out how to run jshint~~ (It's ```gulp jshint```). The CONTRIBUTING.md is a bit out-of-date, so I apologise if I missed a step.

### CODE REVIEW

**Comment by JiDW** [comment]
I wasn't even aware of this way to bind events.

We just do this : 

container.tap = container.click = function(){};

**Comment by marekventur** [comment]
yes, but that only works well if you have only one listener, the on/once approach is a lot more flexible and allows multiple listeners.

**Comment by marekventur** [comment]
But this PR would also allow you to do 
```
container.clicktap = function() {}
```

**Comment by englercj** [comment]
I don't think this is a good idea, if we wanted to combine events we would implement the pointer event API. This is totally non-standard.

**Comment by marekventur** [comment]
Fair enough. Anything I can do to help to move in that direction?

**Comment by englercj** [comment]
There is a lot of work that needs to get done in the interaction manager IMO. I'm thinking of what the best way to do that would be.

In the meantime if you want to unify events like this, just use the standard pointer event names and I would be ok with it, at least temporarily.

**Pull request closed without merging**
